//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp10
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.IssueOrderItems = new HashSet<IssueOrderItem>();
            this.SupplyOrderItems = new HashSet<SupplyOrderItem>();
            this.TransferItems = new HashSet<TransferItem>();
        }
    
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public string UnitOfMeasure { get; set; }
    
        public virtual ICollection<IssueOrderItem> IssueOrderItems { get; set; }
        public virtual ICollection<SupplyOrderItem> SupplyOrderItems { get; set; }
        public virtual ICollection<TransferItem> TransferItems { get; set; }
    }
}
