//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp10
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        public Transfer()
        {
            this.TransferItems = new HashSet<TransferItem>();
        }
    
        public int TransferID { get; set; }
        public Nullable<int> SourceStoreID { get; set; }
        public Nullable<int> DestinationStoreID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
    
        public virtual ICollection<TransferItem> TransferItems { get; set; }
    }
}
